#!/bin/bash
set -eu -o pipefail

export DOCKER_INFLUXDB_INIT_MODE=$DOCKER_INFLUXDB_INIT_MODE
export DOCKER_INFLUXDB_INIT_USERNAME=$DOCKER_INFLUXDB_INIT_USERNAME
export DOCKER_INFLUXDB_INIT_PASSWORD=$DOCKER_INFLUXDB_INIT_PASSWORD
export DOCKER_INFLUXDB_INIT_ORG=$DOCKER_INFLUXDB_INIT_ORG
export DOCKER_INFLUXDB_INIT_BUCKET=$DOCKER_INFLUXDB_INIT_BUCKET
export DOCKER_INFLUXDB_INIT_ADMIN_TOKEN=$DOCKER_INFLUXDB_INIT_ADMIN_TOKEN
export DOCKER_INFLUXDB_INIT_DBV1=$DOCKER_INFLUXDB_INIT_DBV1
export DOCKER_INFLUXDB_INIT_RPV1=$DOCKER_INFLUXDB_INIT_RPV1
# export INFLUXD_TLS_CERT=$INFLUXD_TLS_CERT
# export INFLUXD_TLS_KEY=$INFLUXD_TLS_KEY
echo $DOCKER_INFLUXDB_INIT_MODE
influx setup --skip-verify --bucket ${DOCKER_INFLUXDB_INIT_BUCKET} -t ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN} -o ${DOCKER_INFLUXDB_INIT_ORG} --username="${DOCKER_INFLUXDB_INIT_USERNAME}" --password="${DOCKER_INFLUXDB_INIT_PASSWORD}" --host=http://influxdb:8086 -f

# create db and user
export BUCKET_ID=$(influx bucket list -o ${DOCKER_INFLUXDB_INIT_ORG} -t ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN} | grep -iv "Name" | grep "$DOCKER_INFLUXDB_INIT_BUCKET" | awk '{print $1}')
echo "Create db"
influx v1 dbrp create --skip-verify --db ${DOCKER_INFLUXDB_INIT_DBV1} --rp ${DOCKER_INFLUXDB_INIT_RPV1} --bucket-id ${BUCKET_ID} --default -o ${DOCKER_INFLUXDB_INIT_ORG} -t ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}
# echo "Create user"
# influx v1 auth create --read-bucket ${BUCKET_ID} --write-bucket ${BUCKET_ID} --username influx1 --password influx#1 -o ${DOCKER_INFLUXDB_INIT_ORG} -t ${DOCKER_INFLUXDB_INIT_ADMIN_TOKEN}