{
 "title": "App Monitor",
 "description": "Monitoramento da app",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Host",
    "label": "Host",
    "query": "SHOW TAG VALUES WITH KEY = \"host\""
   },
   {
    "name": "Compose_Project",
    "label": "Projects",
    "query": "SHOW TAG VALUES WITH KEY = \"com.docker.compose.project\""
   },
   {
    "name": "Compose_Services",
    "label": "Services",
    "query": "SHOW TAG VALUES WITH KEY = \"com.docker.compose.service\" WHERE \"com.docker.compose.project\"  =~ /$Compose_Project/"
   }
  ]
 },
 "panels": [
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "App Logs",
   "type": "logs",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "none" ], "type": "fill" }
     ],
     "measurement": "docker_log",
     "select": [
      [
       { "params": [ "message" ], "type": "field" },
       {
        "params": [],
        "type": "distinct"
       }
      ]
     ],
     "tags": [
      { "key": "com.docker.compose.project", "operator": "=~", "value": "/^$Compose_Project$/" },
      { "condition": "AND", "key": "com.docker.compose.service", "operator": "=~", "value": "/^$Compose_Services$/" }
     ],
     "tz": "America/Sao_Paulo"
    }
   ]
  },
  {
   "title": "Usage",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Uso de CPU | $Compose_Project",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$Compose_Project",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.project" ], "type": "tag" }
       ],
       "measurement": "docker_container_cpu",
       "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_cpu\" WHERE (\"com.docker.compose.project\" =~ /^$Compose_Project$/ AND \"com.docker.compose.service\" =~ /^$Compose_Services$/) AND $timeFilter GROUP BY time($__interval) fill(null) tz('America/Sao_Paulo')",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.project", "operator": "=~", "value": "/^$Compose_Project$/" }
       ],
       "tz": "America/Sao_Paulo"
      },
      {
       "alias": "[[tag_com.docker.compose.service]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.service" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_cpu",
       "query": "SELECT mean(\"usage_percent\") FROM \"docker_container_cpu\" WHERE (\"com.docker.compose.project\" =~ /^$Compose_Project$/ AND \"com.docker.compose.service\" =~ /^$Compose_Services$/) AND $timeFilter GROUP BY time($__interval) fill(null) tz('America/Sao_Paulo')",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$Compose_Services$/" }
       ],
       "tz": "America/Sao_Paulo"
      }
     ]
    },
    {
     "title": "Mem Utilizada | $Compose_Project",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "alias": "$Compose_Project",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.project" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.project", "operator": "=~", "value": "/^$Compose_Project$/" }
       ],
       "tz": "America/Sao_Paulo"
      },
      {
       "alias": "[[tag_com.docker.compose.service]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.service" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_mem",
       "select": [
        [
         { "params": [ "usage_percent" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$Compose_Services$/" }
       ],
       "tz": "America/Sao_Paulo"
      }
     ]
    },
    {
     "title": "Traffic | $Compose_Project",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Received - $Compose_Project",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.project" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.project", "operator": "=~", "value": "/^$Compose_Project$/" }
       ]
      },
      {
       "alias": "Transmitted - $Compose_Project",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.project" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.project", "operator": "=~", "value": "/^$Compose_Project$/" }
       ]
      },
      {
       "alias": "Received - [[tag_com.docker.compose.service]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.service" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "rx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$Compose_Services$/" }
       ]
      },
      {
       "alias": "Transmitted - [[tag_com.docker.compose.service]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.service" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_net",
       "select": [
        [
         { "params": [ "tx_bytes" ], "type": "field" },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$Compose_Services$/" }
       ]
      }
     ]
    },
    {
     "title": "Disk IO | $Compose_Project",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "alias": "Read - $Compose_Project",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_read"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.project", "operator": "=~", "value": "/^$Compose_Project$/" }
       ]
      },
      {
       "alias": "Write - $Compose_Project",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_write"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.project", "operator": "=~", "value": "/^$Compose_Project$/" }
       ]
      },
      {
       "alias": "Read - [[tag_com.docker.compose.service]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.service" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_read"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$Compose_Services$/" }
       ]
      },
      {
       "alias": "Write - [[tag_com.docker.compose.service]]",
       "groupBy": [
        { "params": [ "$__interval" ], "type": "time" },
        { "params": [ "com.docker.compose.service" ], "type": "tag" },
        { "params": [ "null" ], "type": "fill" }
       ],
       "measurement": "docker_container_blkio",
       "select": [
        [
         {
          "params": [
           "io_service_bytes_recursive_write"
          ],
          "type": "field"
         },
         {
          "params": [],
          "type": "mean"
         }
        ]
       ],
       "tags": [
        { "key": "com.docker.compose.service", "operator": "=~", "value": "/^$Compose_Services$/" }
       ]
      }
     ]
    }
   ]
  }
 ]
}