{
 "title": "NodeJS Application Dashboard",
 "description": "node.js prometheus client basic metrics",
 "tags": [ "nodejs" ],
 "time": { "from": "2021-03-30T09:32:39.259Z", "to": "2021-03-31T17:32:39.259Z" },
 "templating": {
  "list": [
   { "name": "JOB", "label": "Serviço", "query": "label_values(job)" },
   { "name": "Filters", "label": "FILTER" }
  ]
 },
 "panels": [
  {
   "title": "Process CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "irate(process_cpu_user_seconds_total{job=~\"$JOB\"}[2m]) * 100",
     "legendFormat": "User CPU - {{job}}"
    },
    {
     "expr": "irate(process_cpu_system_seconds_total{job=~\"$JOB\"}[2m]) * 100",
     "legendFormat": "Sys CPU - {{job}}"
    }
   ]
  },
  {
   "title": "Event Loop Lag",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 10, "y": 0 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "nodejs_eventloop_lag_seconds{job=~\"$JOB\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Nodejs Version",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 19, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "nodejs_version_info{job=~\"$JOB\"}",
     "legendFormat": "{{job}}: {{version}}"
    }
   ]
  },
  {
   "title": "Process Restart Times",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 19, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "options": { "reduceOptions": { "calcs": [ "changeCount" ] } },
   "targets": [
    {
     "expr": "process_start_time_seconds{job=~\"$JOB\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Heap Total Detail",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_total_bytes{job=~\"$JOB\"}",
     "legendFormat": "Heap Total - {{job}} - {{space}}"
    }
   ]
  },
  {
   "title": "Heap Used Detail",
   "type": "graph",
   "gridPos": { "h": 14, "w": 8, "x": 8, "y": 7 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_used_bytes{job=~\"$JOB\"}",
     "legendFormat": "Heap Used - {{job}} - {{space}}"
    }
   ]
  },
  {
   "title": "Conexões abertas",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "hex" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "expressjs_number_of_open_connections{job=~\"$JOB\"}",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Active Handlers/Requests Total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nodejs_active_handles_total{job=~\"$JOB\"}",
     "legendFormat": "Active Handler - {{job}}"
    },
    {
     "expr": "nodejs_active_requests_total{job=~\"$JOB\"}",
     "legendFormat": "Active Request - {{job}}"
    }
   ]
  },
  {
   "title": "Heap Available Detail",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "nodejs_heap_space_size_available_bytes{job=~\"$JOB\"}",
     "legendFormat": "Heap Used - {{job}} - {{space}}"
    }
   ]
  },
  {
   "title": "Process Memory Usage",
   "type": "graph",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=~\"$JOB\"}",
     "legendFormat": "Process Memory - {{job}}"
    },
    {
     "expr": "nodejs_heap_size_total_bytes{job=~\"$JOB\"}",
     "legendFormat": "Heap Total - {{job}}"
    },
    {
     "expr": "nodejs_heap_size_used_bytes{job=~\"$JOB\"}",
     "legendFormat": "Heap Used - {{job}}"
    },
    {
     "expr": "nodejs_external_memory_bytes{job=~\"$JOB\"}",
     "legendFormat": "External Memory -{{job}}"
    }
   ]
  }
 ]
}